export interface Product {
  id: string
  category: string
  name: string
  variant: string
  price: number
  type: string
}

export const products: Product[] = [
  // --- Bedroom Sets ---
  { id: "BS-001", category: "Bedroom Sets", name: "Wavy Set", variant: "Double", price: 1105, type: "Bed Set" },
  { id: "BS-002", category: "Bedroom Sets", name: "Wavy Set", variant: "King", price: 1115, type: "Bed Set" },
  { id: "BS-003", category: "Bedroom Sets", name: "New York Set", variant: "Double", price: 1105, type: "Bed Set" },
  { id: "BS-004", category: "Bedroom Sets", name: "New York Set", variant: "King", price: 1115, type: "Bed Set" },
  { id: "BS-005", category: "Bedroom Sets", name: "Zenith Set", variant: "Double", price: 1300, type: "Bed Set" },
  { id: "BS-006", category: "Bedroom Sets", name: "Zenith Set", variant: "King", price: 1310, type: "Bed Set" },
  { id: "BS-007", category: "Bedroom Sets", name: "B02 White Set", variant: "Double", price: 1070, type: "Bed Set" },
  { id: "BS-008", category: "Bedroom Sets", name: "B02 White Set", variant: "King", price: 1080, type: "Bed Set" },
  { id: "BS-009", category: "Bedroom Sets", name: "B01 Set", variant: "Double", price: 1190, type: "Bed Set" },
  { id: "BS-010", category: "Bedroom Sets", name: "B01 Set", variant: "King", price: 1200, type: "Bed Set" },
  { id: "BS-011", category: "Bedroom Sets", name: "B04 Grey Set", variant: "Double", price: 725, type: "Bed Set" },
  { id: "BS-012", category: "Bedroom Sets", name: "B04 Grey Set", variant: "King", price: 735, type: "Bed Set" },
  { id: "BS-013", category: "Bedroom Sets", name: "B04 White Set", variant: "Double", price: 625, type: "Bed Set" },
  { id: "BS-014", category: "Bedroom Sets", name: "B04 White Set", variant: "King", price: 635, type: "Bed Set" },

  // --- 305 Series ---
  { id: "305-001", category: "305 Series", name: "305 White Set", variant: "Double", price: 1135, type: "Bed Set" },
  { id: "305-002", category: "305 Series", name: "305 White Set", variant: "King", price: 1145, type: "Bed Set" },
  { id: "305-003", category: "305 Series", name: "305 Black Set", variant: "Double", price: 1065, type: "Bed Set" },
  { id: "305-004", category: "305 Series", name: "305 Black Set", variant: "King", price: 1075, type: "Bed Set" },
  { id: "305-005", category: "305 Series", name: "305 Grey Paint Set", variant: "Double", price: 1195, type: "Bed Set" },
  { id: "305-006", category: "305 Series", name: "305 Grey Paint Set", variant: "King", price: 1205, type: "Bed Set" },
  { id: "305-007", category: "305 Series", name: "305 Brown Set", variant: "Double", price: 1085, type: "Bed Set" },
  { id: "305-008", category: "305 Series", name: "305 Brown Set", variant: "King", price: 1095, type: "Bed Set" },
  { id: "305-009", category: "305 Series", name: "305 Grey Set", variant: "Double", price: 985, type: "Bed Set" },
  { id: "305-010", category: "305 Series", name: "305 Grey Set", variant: "King", price: 995, type: "Bed Set" },

  // --- Wardrobes ---
  { id: "WR-001", category: "Wardrobes", name: "202", variant: "Single", price: 315, type: "Wardrobe" },
  { id: "WR-002", category: "Wardrobes", name: "202", variant: "200cm", price: 420, type: "Wardrobe" },
  { id: "WR-003", category: "Wardrobes", name: "W01", variant: "Small Double", price: 335, type: "Wardrobe" },
  { id: "WR-004", category: "Wardrobes", name: "W01", variant: "180cm", price: 400, type: "Wardrobe" },
  { id: "WR-005", category: "Wardrobes", name: "W02", variant: "Double", price: 335, type: "Wardrobe" },
  { id: "WR-006", category: "Wardrobes", name: "W02", variant: "200cm", price: 420, type: "Wardrobe" },
  { id: "WR-007", category: "Wardrobes", name: "W03", variant: "King", price: 345, type: "Wardrobe" },
  { id: "WR-008", category: "Wardrobes", name: "W03", variant: "240cm", price: 490, type: "Wardrobe" },
  { id: "WR-009", category: "Wardrobes", name: "W04", variant: "Superking", price: 400, type: "Wardrobe" },
  { id: "WR-010", category: "Wardrobes", name: "W04", variant: "150cm", price: 370, type: "Wardrobe" },
  { id: "WR-011", category: "Wardrobes", name: "W07", variant: "Double", price: 365, type: "Wardrobe" },
  { id: "WR-012", category: "Wardrobes", name: "W07", variant: "200cm", price: 420, type: "Wardrobe" },
  { id: "WR-013", category: "Wardrobes", name: "W10", variant: "King", price: 375, type: "Wardrobe" },
  { id: "WR-014", category: "Wardrobes", name: "W10", variant: "180cm", price: 450, type: "Wardrobe" },
  { id: "WR-015", category: "Wardrobes", name: "Wavy", variant: "Double", price: 335, type: "Wardrobe" },
  { id: "WR-016", category: "Wardrobes", name: "Wavy", variant: "180cm", price: 400, type: "Wardrobe" },
  { id: "WR-017", category: "Wardrobes", name: "KY02", variant: "King", price: 345, type: "Wardrobe" },
  { id: "WR-018", category: "Wardrobes", name: "KY02", variant: "90cm", price: 160, type: "Wardrobe" },
  { id: "WR-019", category: "Wardrobes", name: "KY03", variant: "Double", price: 350, type: "Wardrobe" },
  { id: "WR-020", category: "Wardrobes", name: "KY03", variant: "135cm", price: 200, type: "Wardrobe" },
  { id: "WR-021", category: "Wardrobes", name: "KY04", variant: "King", price: 360, type: "Wardrobe" },
  { id: "WR-022", category: "Wardrobes", name: "KY04", variant: "180cm", price: 300, type: "Wardrobe" },
  { id: "WR-023", category: "Wardrobes", name: "KY05", variant: "Double", price: 400, type: "Wardrobe" },
  { id: "WR-024", category: "Wardrobes", name: "KY05", variant: "315cm", price: 340, type: "Wardrobe" },

  // --- Sofa Beds ---
  { id: "SB-001", category: "Sofa Beds", name: "Lotto", variant: "3 Seater", price: 500, type: "Sofa Bed" },
  { id: "SB-002", category: "Sofa Beds", name: "Lotto", variant: "2 Seater", price: 400, type: "Sofa Bed" },
  { id: "SB-003", category: "Sofa Beds", name: "Lotto", variant: "1 Seater", price: 300, type: "Sofa Bed" },
  { id: "SB-004", category: "Sofa Beds", name: "Lotto", variant: "3+2", price: 800, type: "Sofa Bed" },
  { id: "SB-005", category: "Sofa Beds", name: "Lotto", variant: "3+2+1", price: 1100, type: "Sofa Bed" },
  { id: "SB-006", category: "Sofa Beds", name: "Lotto", variant: "3+C+2", price: 900, type: "Sofa Bed" },
  { id: "SB-007", category: "Sofa Beds", name: "Lotto", variant: "3+Relax", price: 750, type: "Sofa Bed" },

  { id: "SB-008", category: "Sofa Beds", name: "Punto", variant: "3 Seater", price: 550, type: "Sofa Bed" },
  { id: "SB-009", category: "Sofa Beds", name: "Punto", variant: "2 Seater", price: 450, type: "Sofa Bed" },
  { id: "SB-010", category: "Sofa Beds", name: "Punto", variant: "1 Seater", price: 350, type: "Sofa Bed" },
  { id: "SB-011", category: "Sofa Beds", name: "Punto", variant: "3+2", price: 900, type: "Sofa Bed" },
  { id: "SB-012", category: "Sofa Beds", name: "Punto", variant: "3+2+1", price: 1250, type: "Sofa Bed" },
  { id: "SB-013", category: "Sofa Beds", name: "Punto", variant: "3+C+2", price: 950, type: "Sofa Bed" },
  { id: "SB-014", category: "Sofa Beds", name: "Punto", variant: "3+Relax", price: 800, type: "Sofa Bed" },

  { id: "SB-015", category: "Sofa Beds", name: "Pera", variant: "3 Seater", price: 500, type: "Sofa Bed" },
  { id: "SB-016", category: "Sofa Beds", name: "Pera", variant: "2 Seater", price: 400, type: "Sofa Bed" },
  { id: "SB-017", category: "Sofa Beds", name: "Pera", variant: "1 Seater", price: 300, type: "Sofa Bed" },
  { id: "SB-018", category: "Sofa Beds", name: "Pera", variant: "3+2", price: 800, type: "Sofa Bed" },
  { id: "SB-019", category: "Sofa Beds", name: "Pera", variant: "3+2+1", price: 1100, type: "Sofa Bed" },
  { id: "SB-020", category: "Sofa Beds", name: "Pera", variant: "3+C+2", price: 900, type: "Sofa Bed" },

  { id: "SB-021", category: "Sofa Beds", name: "Focus", variant: "3 Seater", price: 550, type: "Sofa Bed" },
  { id: "SB-022", category: "Sofa Beds", name: "Focus", variant: "2 Seater", price: 450, type: "Sofa Bed" },
  { id: "SB-023", category: "Sofa Beds", name: "Focus", variant: "1 Seater", price: 275, type: "Sofa Bed" },
  { id: "SB-024", category: "Sofa Beds", name: "Focus", variant: "3+2", price: 900, type: "Sofa Bed" },
  { id: "SB-025", category: "Sofa Beds", name: "Focus", variant: "3+2+1", price: 1175, type: "Sofa Bed" },
  { id: "SB-026", category: "Sofa Beds", name: "Focus", variant: "3+C+2", price: 1000, type: "Sofa Bed" },

  { id: "SB-027", category: "Sofa Beds", name: "Milano", variant: "3 Seater", price: 525, type: "Sofa Bed" },
  { id: "SB-028", category: "Sofa Beds", name: "Milano", variant: "2 Seater", price: 425, type: "Sofa Bed" },
  { id: "SB-029", category: "Sofa Beds", name: "Milano", variant: "1 Seater", price: 275, type: "Sofa Bed" },
  { id: "SB-030", category: "Sofa Beds", name: "Milano", variant: "3+2", price: 850, type: "Sofa Bed" },
  { id: "SB-031", category: "Sofa Beds", name: "Milano", variant: "3+2+1", price: 1125, type: "Sofa Bed" },
  { id: "SB-032", category: "Sofa Beds", name: "Milano", variant: "3+C+2", price: 950, type: "Sofa Bed" },

  { id: "SB-033", category: "Sofa Beds", name: "Karmen", variant: "3 Seater", price: 265, type: "Sofa Bed" },
  { id: "SB-034", category: "Sofa Beds", name: "Karmen", variant: "2 Seater", price: 245, type: "Sofa Bed" },
  { id: "SB-035", category: "Sofa Beds", name: "Karmen", variant: "3+2", price: 510, type: "Sofa Bed" },

  { id: "SB-036", category: "Sofa Beds", name: "Lidya", variant: "3 Seater", price: 425, type: "Sofa Bed" },
  { id: "SB-037", category: "Sofa Beds", name: "Lidya", variant: "2 Seater", price: 325, type: "Sofa Bed" },
  { id: "SB-038", category: "Sofa Beds", name: "Lidya", variant: "3+2", price: 675, type: "Sofa Bed" },

  { id: "SB-039", category: "Sofa Beds", name: "Vida", variant: "3 Seater", price: 450, type: "Sofa Bed" },
  { id: "SB-040", category: "Sofa Beds", name: "Vida", variant: "2 Seater", price: 350, type: "Sofa Bed" },
  { id: "SB-041", category: "Sofa Beds", name: "Vida", variant: "3+2", price: 700, type: "Sofa Bed" },
  { id: "SB-042", category: "Sofa Beds", name: "Vida", variant: "3+C+2", price: 800, type: "Sofa Bed" },

  { id: "SB-043", category: "Sofa Beds", name: "Oval", variant: "3 Seater", price: 450, type: "Sofa Bed" },
  { id: "SB-044", category: "Sofa Beds", name: "Oval", variant: "2 Seater", price: 350, type: "Sofa Bed" },
  { id: "SB-045", category: "Sofa Beds", name: "Oval", variant: "3+2", price: 700, type: "Sofa Bed" },
  { id: "SB-046", category: "Sofa Beds", name: "Oval", variant: "3+C+2", price: 800, type: "Sofa Bed" },

  { id: "SB-047", category: "Sofa Beds", name: "Classic", variant: "3 Seater", price: 650, type: "Sofa Bed" },
  { id: "SB-048", category: "Sofa Beds", name: "Classic", variant: "2 Seater", price: 550, type: "Sofa Bed" },
  { id: "SB-049", category: "Sofa Beds", name: "Classic", variant: "1 Seater", price: 400, type: "Sofa Bed" },
  { id: "SB-050", category: "Sofa Beds", name: "Classic", variant: "3+2", price: 1100, type: "Sofa Bed" },
  { id: "SB-051", category: "Sofa Beds", name: "Classic", variant: "3+2+1", price: 1400, type: "Sofa Bed" },

  // --- Drawers ---
  { id: "DR-001", category: "Drawers", name: "KY500", variant: "80cm", price: 100, type: "Drawer" },
  { id: "DR-002", category: "Drawers", name: "D04", variant: "80cm", price: 130, type: "Drawer" },
  { id: "DR-003", category: "Drawers", name: "D05", variant: "80cm", price: 140, type: "Drawer" },
  { id: "DR-004", category: "Drawers", name: "D06", variant: "80cm", price: 150, type: "Drawer" },
  { id: "DR-005", category: "Drawers", name: "D07", variant: "120cm", price: 180, type: "Drawer" },
  { id: "DR-006", category: "Drawers", name: "D09", variant: "120cm", price: 200, type: "Drawer" },
  { id: "DR-007", category: "Drawers", name: "CD3+3", variant: "120cm", price: 125, type: "Drawer" },

  // --- Living ---
  { id: "LV-001", category: "Living", name: "TV01", variant: "180cm", price: 220, type: "TV Unit" },
  { id: "LV-002", category: "Living", name: "TV01", variant: "150cm", price: 180, type: "TV Unit" },
  { id: "LV-003", category: "Living", name: "TV02", variant: "180cm", price: 220, type: "TV Unit" },
  { id: "LV-004", category: "Living", name: "TV02", variant: "150cm", price: 180, type: "TV Unit" },
  { id: "LV-005", category: "Living", name: "CT01", variant: "120cm", price: 180, type: "Coffee Table" },
  { id: "LV-006", category: "Living", name: "CT02", variant: "120cm", price: 180, type: "Coffee Table" },
  
  { id: "LV-007", category: "Living", name: "XE02A", variant: "80cm", price: 125, type: "Shoe Rack" },
  { id: "LV-008", category: "Living", name: "XE02B", variant: "120cm", price: 150, type: "Shoe Rack" },
  { id: "LV-009", category: "Living", name: "Combi", variant: "90cm", price: 85, type: "Shoe Rack" },
  { id: "LV-010", category: "Living", name: "XE13-1M", variant: "60cm", price: 75, type: "Shoe Rack" },
  { id: "LV-011", category: "Living", name: "XE14-1M", variant: "60cm", price: 85, type: "Shoe Rack" },
  { id: "LV-012", category: "Living", name: "XE34", variant: "60cm", price: 60, type: "Shoe Rack" },
  { id: "LV-013", category: "Living", name: "XE42", variant: "60cm", price: 65, type: "Shoe Rack" },
  { id: "LV-014", category: "Living", name: "XE41", variant: "60cm", price: 70, type: "Shoe Rack" },
  { id: "LV-015", category: "Living", name: "XE51", variant: "60cm", price: 80, type: "Shoe Rack" },

  { id: "LV-016", category: "Living", name: "380", variant: "120cm", price: 350, type: "Wall Unit" },
  { id: "LV-017", category: "Living", name: "1703", variant: "80cm", price: 250, type: "Wall Unit" },
  { id: "LV-018", category: "Living", name: "1709", variant: "80cm", price: 250, type: "Wall Unit" },
  // --- Dining Tables (Mapped to Living) ---
  { id: "LV-101", category: "Living", name: "Daisy", variant: "160 Steel", price: 210, type: "Dining Table" },
  { id: "LV-102", category: "Living", name: "Daisy", variant: "160 Gold", price: 220, type: "Dining Table" },
  { id: "LV-103", category: "Living", name: "Daisy", variant: "120 Steel", price: 190, type: "Dining Table" },
  { id: "LV-104", category: "Living", name: "Daisy", variant: "120 Gold", price: 200, type: "Dining Table" },
  { id: "LV-105", category: "Living", name: "Scorpio", variant: "Non-Extending", price: 89, type: "Dining Table" },
  { id: "LV-106", category: "Living", name: "Scorpio", variant: "Extending", price: 165, type: "Dining Table" },
  { id: "LV-107", category: "Living", name: "Amber", variant: "120cm Metal Leg", price: 99, type: "Dining Table" },
  { id: "LV-108", category: "Living", name: "Amber", variant: "150cm Metal Leg", price: 119, type: "Dining Table" },
  { id: "LV-109", category: "Living", name: "Amber", variant: "80cm Square", price: 99, type: "Dining Table" },
  { id: "LV-110", category: "Living", name: "Stello", variant: "Extending", price: 195, type: "Dining Table" },
  { id: "LV-111", category: "Living", name: "Husty Stone", variant: "130cm", price: 150, type: "Dining Table" },
  { id: "LV-112", category: "Living", name: "Husty Stone", variant: "150cm", price: 160, type: "Dining Table" },
  { id: "LV-113", category: "Living", name: "Husty Stone", variant: "170cm", price: 170, type: "Dining Table" },
  { id: "LV-114", category: "Living", name: "Husty Glass", variant: "150cm", price: 160, type: "Dining Table" },
  { id: "LV-115", category: "Living", name: "Husty Glass", variant: "130cm", price: 150, type: "Dining Table" },
  { id: "LV-116", category: "Living", name: "Helen", variant: "Big 170cm", price: 99, type: "Dining Table" },
  { id: "LV-117", category: "Living", name: "Helen", variant: "Small 130cm", price: 95, type: "Dining Table" },
  { id: "LV-118", category: "Living", name: "Windsor", variant: "Black", price: 85, type: "Dining Table" },
  { id: "LV-119", category: "Living", name: "Windsor", variant: "Gold", price: 85, type: "Dining Table" },
  { id: "LV-120", category: "Living", name: "Oval", variant: "Black", price: 55, type: "Dining Table" },
  { id: "LV-121", category: "Living", name: "Oval", variant: "Gold", price: 55, type: "Dining Table" },
  { id: "LV-122", category: "Living", name: "Ruby", variant: "120cm", price: 89, type: "Dining Table" },
  { id: "LV-123", category: "Living", name: "Ruby", variant: "150cm", price: 105, type: "Dining Table" },
  { id: "LV-124", category: "Living", name: "Madrid", variant: "Gold Frame Set", price: 179, type: "Dining Table" },
  { id: "LV-125", category: "Living", name: "Ace", variant: "Dining Set", price: 129, type: "Dining Table" },
  { id: "LV-126", category: "Living", name: "Louis", variant: "160 Stone", price: 259, type: "Dining Table" },

  // --- Dining Chairs (Mapped to Living) ---
  { id: "LV-201", category: "Living", name: "Bruno", variant: "Gold", price: 79, type: "Dining Chair" },
  { id: "LV-202", category: "Living", name: "Bruno", variant: "Steel", price: 75, type: "Dining Chair" },
  { id: "LV-203", category: "Living", name: "Posh", variant: "Gold", price: 95, type: "Dining Chair" },
  { id: "LV-204", category: "Living", name: "Posh", variant: "Chrome", price: 90, type: "Dining Chair" },
  { id: "LV-205", category: "Living", name: "Palm", variant: "Gold", price: 75, type: "Dining Chair" },
  { id: "LV-206", category: "Living", name: "Palm", variant: "Chrome", price: 75, type: "Dining Chair" },
  { id: "LV-207", category: "Living", name: "Morocan", variant: "Standard", price: 45, type: "Dining Chair" },
  { id: "LV-208", category: "Living", name: "Tuilip", variant: "Gold Feet", price: 39, type: "Dining Chair" },
  { id: "LV-209", category: "Living", name: "Tuilip", variant: "Black Leg", price: 39, type: "Dining Chair" },
  { id: "LV-210", category: "Living", name: "Tuilip", variant: "Chrome Leg", price: 39, type: "Dining Chair" },
  { id: "LV-211", category: "Living", name: "Tuilip", variant: "Full Gold Leg", price: 45, type: "Dining Chair" },
  { id: "LV-212", category: "Living", name: "Ivy", variant: "Standard", price: 45, type: "Dining Chair" },
  { id: "LV-213", category: "Living", name: "Polo", variant: "Plain", price: 39, type: "Dining Chair" },
  { id: "LV-214", category: "Living", name: "Luxury", variant: "Square", price: 39, type: "Dining Chair" },
  { id: "LV-215", category: "Living", name: "Happy", variant: "Square", price: 29, type: "Dining Chair" },
  { id: "LV-216", category: "Living", name: "Misty", variant: "Standard", price: 26, type: "Dining Chair" },
  { id: "LV-217", category: "Living", name: "Bella", variant: "Standard", price: 29, type: "Dining Chair" },
  { id: "LV-218", category: "Living", name: "Laura", variant: "Diamond Chrome", price: 29, type: "Dining Chair" },
  { id: "LV-219", category: "Living", name: "Laura", variant: "Diamond Black", price: 25, type: "Dining Chair" },
  { id: "LV-220", category: "Living", name: "Lina", variant: "Gold Feet", price: 29, type: "Dining Chair" },
  { id: "LV-221", category: "Living", name: "Lina", variant: "Full Black Legs", price: 29, type: "Dining Chair" },
  { id: "LV-222", category: "Living", name: "Lotus", variant: "Gold", price: 27.50, type: "Dining Chair" },
  { id: "LV-223", category: "Living", name: "Lotus", variant: "Black", price: 25, type: "Dining Chair" },
  { id: "LV-224", category: "Living", name: "Jordan", variant: "Gold", price: 45, type: "Dining Chair" },
  { id: "LV-225", category: "Living", name: "Jordan", variant: "Chrome", price: 45, type: "Dining Chair" },
  { id: "LV-226", category: "Living", name: "Roxy", variant: "Standard", price: 69, type: "Dining Chair" },
  { id: "LV-227", category: "Living", name: "Julie", variant: "Standard", price: 85, type: "Dining Chair" },
  { id: "LV-228", category: "Living", name: "Raphael", variant: "Standard", price: 59, type: "Dining Chair" },
  { id: "LV-229", category: "Living", name: "Verbier", variant: "Standard", price: 59, type: "Dining Chair" },
  { id: "LV-230", category: "Living", name: "Lara", variant: "Gold", price: 65, type: "Dining Chair" },
  { id: "LV-231", category: "Living", name: "Lara", variant: "Silver", price: 65, type: "Dining Chair" },
  { id: "LV-232", category: "Living", name: "Dragon", variant: "Silver", price: 89, type: "Dining Chair" },
  { id: "LV-233", category: "Living", name: "Dragon", variant: "Gold", price: 95, type: "Dining Chair" },
  { id: "LV-234", category: "Living", name: "Greek", variant: "Silver", price: 89, type: "Dining Chair" },
  { id: "LV-235", category: "Living", name: "Greek", variant: "Gold", price: 95, type: "Dining Chair" },
  { id: "LV-236", category: "Living", name: "Belvedare", variant: "Silver", price: 70, type: "Dining Chair" },
  { id: "LV-237", category: "Living", name: "Belvedare", variant: "Gold", price: 75, type: "Dining Chair" },

  // --- Coffee Tables (Mapped to Living) ---
  { id: "LV-301", category: "Living", name: "Daisy", variant: "Steel CT", price: 179, type: "Coffee Table" },
  { id: "LV-302", category: "Living", name: "Daisy", variant: "Gold CT", price: 189, type: "Coffee Table" },
  { id: "LV-303", category: "Living", name: "Florida", variant: "CT Only", price: 135, type: "Coffee Table" },
  { id: "LV-304", category: "Living", name: "Florida", variant: "CT+ST Set", price: 169, type: "Coffee Table" },
  { id: "LV-305", category: "Living", name: "Amber", variant: "120cm", price: 75, type: "Coffee Table" },
  { id: "LV-306", category: "Living", name: "Amber", variant: "90x90cm", price: 89, type: "Coffee Table" },
  { id: "LV-307", category: "Living", name: "Amber", variant: "Set 2+1", price: 145, type: "Coffee Table" },
  { id: "LV-308", category: "Living", name: "Amber", variant: "Nest", price: 99, type: "Coffee Table" },
  { id: "LV-309", category: "Living", name: "Windsor", variant: "Black", price: 50, type: "Coffee Table" },
  { id: "LV-310", category: "Living", name: "Windsor", variant: "Gold", price: 50, type: "Coffee Table" },
  { id: "LV-311", category: "Living", name: "Oval", variant: "Black CT", price: 35, type: "Coffee Table" },
  { id: "LV-312", category: "Living", name: "Oval", variant: "Gold CT", price: 35, type: "Coffee Table" },
  { id: "LV-313", category: "Living", name: "Oval", variant: "2+1 Black", price: 110, type: "Coffee Table" },
  { id: "LV-314", category: "Living", name: "Oval", variant: "2+1 Gold", price: 110, type: "Coffee Table" },
  { id: "LV-315", category: "Living", name: "Oval", variant: "Black Nest", price: 65, type: "Coffee Table" },
  { id: "LV-316", category: "Living", name: "Oval", variant: "Gold Nest", price: 75, type: "Coffee Table" },
  { id: "LV-317", category: "Living", name: "Lucy", variant: "Standard", price: 59, type: "Coffee Table" },
  { id: "LV-318", category: "Living", name: "Lucy", variant: "2+1 Set", price: 99, type: "Coffee Table" },
  { id: "LV-319", category: "Living", name: "Rumy", variant: "Nest", price: 75, type: "Coffee Table" },
  { id: "LV-320", category: "Living", name: "Eartha", variant: "Small 90cm", price: 45, type: "Coffee Table" },
  { id: "LV-321", category: "Living", name: "Eartha", variant: "Big 110cm", price: 55, type: "Coffee Table" },
  { id: "LV-322", category: "Living", name: "Compact", variant: "Standard", price: 35, type: "Coffee Table" },
  { id: "LV-323", category: "Living", name: "Budget", variant: "Small 90cm", price: 39, type: "Coffee Table" },
  { id: "LV-324", category: "Living", name: "Budget", variant: "Big 110cm", price: 45, type: "Coffee Table" },
  { id: "LV-325", category: "Living", name: "Salty", variant: "Standard", price: 65, type: "Coffee Table" },
  { id: "LV-326", category: "Living", name: "Sugar", variant: "Standard", price: 39, type: "Coffee Table" },
  { id: "LV-327", category: "Living", name: "Lemon", variant: "NT", price: 45, type: "Coffee Table" },
  { id: "LV-328", category: "Living", name: "Iva", variant: "Standard", price: 55, type: "Coffee Table" },
  { id: "LV-329", category: "Living", name: "Zoe", variant: "Standard", price: 65, type: "Coffee Table" },
  { id: "LV-330", category: "Living", name: "Zoe", variant: "Set of 2", price: 49, type: "Coffee Table" },
  { id: "LV-331", category: "Living", name: "Cooper", variant: "Set of 2", price: 50, type: "Coffee Table" },
  { id: "LV-332", category: "Living", name: "Mario", variant: "Set of 2", price: 65, type: "Coffee Table" },
  { id: "LV-333", category: "Living", name: "Circle", variant: "Set of 2 Gold", price: 65, type: "Coffee Table" },
  { id: "LV-334", category: "Living", name: "Circle", variant: "Set of 2 Black", price: 60, type: "Coffee Table" },
  { id: "LV-335", category: "Living", name: "Clark", variant: "Set of 3", price: 89, type: "Coffee Table" },
  { id: "LV-336", category: "Living", name: "Nyra", variant: "Gold 100cm", price: 59, type: "Coffee Table" },
  { id: "LV-337", category: "Living", name: "Nyra", variant: "Black 100cm", price: 55, type: "Coffee Table" },
  { id: "LV-338", category: "Living", name: "Nyra", variant: "Gold 120cm", price: 65, type: "Coffee Table" },
  { id: "LV-339", category: "Living", name: "Nyra", variant: "Black 120cm", price: 59, type: "Coffee Table" },
  { id: "LV-340", category: "Living", name: "Vina", variant: "Gold CT 80cm", price: 55, type: "Coffee Table" },
  { id: "LV-341", category: "Living", name: "Vina", variant: "Black CT 80cm", price: 55, type: "Coffee Table" },
  { id: "LV-342", category: "Living", name: "Vina", variant: "Gold CT 55cm", price: 35, type: "Coffee Table" },
  { id: "LV-343", category: "Living", name: "Vina", variant: "Black CT 55cm", price: 35, type: "Coffee Table" },
  { id: "LV-344", category: "Living", name: "Vina", variant: "Gold ST", price: 35, type: "Coffee Table" },
  { id: "LV-345", category: "Living", name: "Vina", variant: "Black ST", price: 35, type: "Coffee Table" },

  // --- Hampton Range (Mapped to Drawers/Living) ---
  { id: "LV-401", category: "Living", name: "Hampton", variant: "2 Door 1 Drawer", price: 55, type: "Cabinet" },
  { id: "LV-402", category: "Living", name: "Hampton", variant: "2 Drawer Bench", price: 45, type: "Bench" },
  { id: "DR-403", category: "Drawers", name: "Hampton", variant: "3 Drawer", price: 60, type: "Drawer" },
  { id: "DR-404", category: "Drawers", name: "Hampton", variant: "4 Drawer", price: 75, type: "Drawer" },
  { id: "LV-405", category: "Living", name: "Hampton", variant: "160cm TV Unit", price: 119, type: "TV Unit" },
  { id: "LV-406", category: "Living", name: "Hampton", variant: "180cm TV Unit", price: 129, type: "TV Unit" },

  // --- Hilton & Smart Italian (Mapped to Living) ---
  { id: "LV-501", category: "Living", name: "Hilton", variant: "2 Door Cabinet", price: 359, type: "Cabinet" },
  { id: "LV-502", category: "Living", name: "Hilton", variant: "1 Door Cabinet", price: 265, type: "Cabinet" },
  { id: "LV-503", category: "Living", name: "Hilton", variant: "TV Unit", price: 259, type: "TV Unit" },
  { id: "LV-504", category: "Living", name: "Hilton", variant: "Lamp Table", price: 115, type: "Table" },
  { id: "LV-505", category: "Living", name: "Hilton", variant: "Coffee Table", price: 145, type: "Coffee Table" },
  { id: "LV-506", category: "Living", name: "Hilton", variant: "Dining Table (Ext)", price: 320, type: "Dining Table" },
  { id: "LV-507", category: "Living", name: "Hilton", variant: "Fixed 4Leg DT", price: 155, type: "Dining Table" },
  { id: "LV-508", category: "Living", name: "Hilton", variant: "4 Leg (Ext) DT", price: 259, type: "Dining Table" },
  { id: "LV-509", category: "Living", name: "Hilton", variant: "3/D Sideboard", price: 349, type: "Sideboard" },
  { id: "LV-510", category: "Living", name: "Hilton", variant: "4/D W/LED", price: 395, type: "Cabinet" },
  { id: "LV-511", category: "Living", name: "Hilton", variant: "Mirror S/Board", price: 85, type: "Mirror" },
  { id: "LV-512", category: "Living", name: "Smart", variant: "2 Door Cabinet", price: 359, type: "Cabinet" },
  { id: "LV-513", category: "Living", name: "Smart", variant: "1 Door Cabinet", price: 235, type: "Cabinet" },
  { id: "LV-514", category: "Living", name: "Smart", variant: "TV Unit", price: 195, type: "TV Unit" },
  { id: "LV-515", category: "Living", name: "Smart", variant: "Coffee Table", price: 145, type: "Coffee Table" },
  { id: "LV-516", category: "Living", name: "Smart", variant: "Dining Table (Fixed)", price: 259, type: "Dining Table" },
  { id: "LV-517", category: "Living", name: "Smart", variant: "4/D W/LED", price: 375, type: "Cabinet" },

  // --- Bar Stools (Mapped to Living) ---
  { id: "LV-601", category: "Living", name: "Aryan", variant: "Standard", price: 29, type: "Bar Stool" },
  { id: "LV-602", category: "Living", name: "Milo", variant: "Standard", price: 32, type: "Bar Stool" },
  { id: "LV-603", category: "Living", name: "Wendy", variant: "Standard", price: 32, type: "Bar Stool" },
  { id: "LV-604", category: "Living", name: "Smart", variant: "Bar Stool", price: 35, type: "Bar Stool" },
  { id: "LV-605", category: "Living", name: "Posh", variant: "Gold Stool", price: 95, type: "Bar Stool" },
  { id: "LV-606", category: "Living", name: "Posh", variant: "Chrome Stool", price: 90, type: "Bar Stool" },

  // --- Sofa Beds & Sofas ---
  { id: "SB-101", category: "Sofa Beds", name: "Kevin", variant: "3 Seater", price: 259, type: "Sofa" },
  { id: "SB-102", category: "Sofa Beds", name: "Kevin", variant: "2 Seater", price: 249, type: "Sofa" },
  { id: "SB-103", category: "Sofa Beds", name: "Donence", variant: "3 Seater", price: 210, type: "Sofa" },
  { id: "SB-104", category: "Sofa Beds", name: "Donence", variant: "2 Seater", price: 200, type: "Sofa" },
  { id: "SB-105", category: "Sofa Beds", name: "Berlin", variant: "3+2 Set", price: 699, type: "Sofa" },
  { id: "SB-106", category: "Sofa Beds", name: "Veyron", variant: "3+2 Set", price: 235, type: "Sofa" },
  { id: "SB-107", category: "Sofa Beds", name: "Destaan", variant: "3+2 Set", price: 750, type: "Sofa" },
  { id: "SB-108", category: "Sofa Beds", name: "Zeytin", variant: "3 Seater", price: 239, type: "Sofa" },
  { id: "SB-109", category: "Sofa Beds", name: "Zeytin", variant: "2 Seater", price: 229, type: "Sofa" },
  { id: "SB-110", category: "Sofa Beds", name: "Kia", variant: "3+2 Set", price: 575, type: "Sofa" },
  { id: "SB-111", category: "Sofa Beds", name: "Clara", variant: "3+2 Set", price: 450, type: "Sofa" },
  { id: "SB-112", category: "Sofa Beds", name: "Ocean", variant: "3+2 Set", price: 545, type: "Sofa" },

  // --- Beds (Mapped to Bedroom Sets) ---
  { id: "BS-101", category: "Bedroom Sets", name: "Maya", variant: "Single", price: 179, type: "Bed Frame" },
  { id: "BS-102", category: "Bedroom Sets", name: "Maya", variant: "Double", price: 189, type: "Bed Frame" },
  { id: "BS-103", category: "Bedroom Sets", name: "Maya", variant: "King", price: 199, type: "Bed Frame" },
  { id: "BS-104", category: "Bedroom Sets", name: "Ottoman", variant: "Single", price: 115, type: "Bed Frame" },
  { id: "BS-105", category: "Bedroom Sets", name: "Ottoman", variant: "Double", price: 125, type: "Bed Frame" },
  { id: "BS-106", category: "Bedroom Sets", name: "Ottoman", variant: "4ft", price: 125, type: "Bed Frame" },
  { id: "BS-107", category: "Bedroom Sets", name: "Maple", variant: "Single", price: 105, type: "Bed Frame" },
  { id: "BS-108", category: "Bedroom Sets", name: "Maple", variant: "Double", price: 115, type: "Bed Frame" },
  { id: "BS-109", category: "Bedroom Sets", name: "Maple", variant: "King", price: 125, type: "Bed Frame" },
  { id: "BS-110", category: "Bedroom Sets", name: "Mozart", variant: "Single", price: 65, type: "Bed Frame" },
  { id: "BS-111", category: "Bedroom Sets", name: "Mozart", variant: "Double", price: 65, type: "Bed Frame" },
  { id: "BS-112", category: "Bedroom Sets", name: "Dirty Oak", variant: "Single", price: 65, type: "Bed Frame" },
  { id: "BS-113", category: "Bedroom Sets", name: "Dirty Oak", variant: "Double", price: 70, type: "Bed Frame" },
  { id: "BS-114", category: "Bedroom Sets", name: "Dirty Oak", variant: "King", price: 75, type: "Bed Frame" },
  { id: "BS-115", category: "Bedroom Sets", name: "Diva", variant: "Single", price: 70, type: "Bed Frame" },
  { id: "BS-116", category: "Bedroom Sets", name: "Diva", variant: "Double", price: 80, type: "Bed Frame" },

  // --- Clearance Items ---
  { id: "BS-200", category: "Bedroom Sets", name: "Berlin", variant: "King", price: 350, type: "Bed Frame" },
  { id: "BS-201", category: "Bedroom Sets", name: "Milano", variant: "King", price: 350, type: "Bed Frame" },
  { id: "BS-202", category: "Bedroom Sets", name: "Eagle", variant: "Bunk", price: 225, type: "Bed Frame" },
  { id: "BS-203", category: "Bedroom Sets", name: "Lorcan", variant: "150cm", price: 350, type: "Bed Frame" },
  { id: "BS-204", category: "Bedroom Sets", name: "New Boni", variant: "160cm", price: 75, type: "Bed Frame" },
  { id: "LV-701", category: "Living", name: "Mistral", variant: "2 Door Cabinet", price: 275, type: "Cabinet" },
  { id: "LV-702", category: "Living", name: "Mistral", variant: "Lamp Table", price: 125, type: "Table" },
  { id: "BS-205", category: "Bedroom Sets", name: "Alice", variant: "King", price: 150, type: "Bed Frame" },
  { id: "LV-703", category: "Living", name: "Arcade", variant: "120cm DT", price: 120, type: "Dining Table" },
  { id: "LV-704", category: "Living", name: "Arcade", variant: "160cm DT", price: 129, type: "Dining Table" },
]

export const categories = [
  "All",
  "Bedroom Sets",
  "305 Series",
  "Wardrobes",
  "Sofa Beds",
  "Drawers",
  "Living",
] as const

export type Category = (typeof categories)[number]
